import type { PrismaClient } from "@prisma/client";

// BR-01: the official Ticket Number is generated by the backend and must be unique.
// Format: TKT-YYYY-NNNNNN, sequential per year, backed by a DB row updated atomically.
export async function generateTicketNumber(
  prisma: PrismaClient,
  date: Date = new Date()
): Promise<string> {
  const year = date.getFullYear();
  const seq = await prisma.ticketSequence.upsert({
    where: { year },
    create: { year, value: 1 },
    update: { value: { increment: 1 } },
  });
  const padded = String(seq.value).padStart(6, "0");
  return `TKT-${year}-${padded}`;
}
